### PR TITLE
Remove usage of `.public`

### PR DESCRIPTION
**Pull request by filiptronicek**
Adhere to changes made in https://github.com/microsoft/vscode/commit/d56f8a8ddee825a784b8964cae91ce6e60b6b844

## How to test

1. Open a repository with ports config in the preview environment: https://ft-test-ports-public.preview.gitpod-dev.com/workspaces
2. play around with ports' visibility. Make sure toggling and displaying correctly reflects the port's public/private state.

### CODE REVIEW

**Comment by jeanp413** [comment]
@mustard-mh could you review it :pray:

**Comment by mustard-mh** [comment]
Could you add **How to Test** section 🙏 ? We need to test if it won't break ports' operations. @filiptronicek

**Comment by filiptronicek** [comment]
@mustard-mh added ✅ 🙏

**Review by mustard-mh — APPROVED** [review]
Tested it all good 👍 

But found some bugs (maybe I tested it wrong) with ports tunnel with local-companion, will file an issue to track it.

**Pull request merged**
