### PR TITLE
Switch workbench preferred color themes to Gitpod Light/Dark 

### PR DESCRIPTION
**Pull request by Shulammite-Aso**
This PR fixes  https://github.com/gitpod-io/gitpod/issues/6403

### CODE REVIEW

**Comment by Shulammite-Aso** [comment]
Hi @gtsiolis @akosyakov @jeanp413 please have a look

**Comment by jeanp413** [comment]
@Shulammite-Aso you should also set `"window.autoDetectColorScheme": true` so that `workbench.preferredLightColorTheme` and `workbench.preferredDarkColorTheme` take effect.

**Comment by Shulammite-Aso** [comment]
> @Shulammite-Aso you should also set `"window.autoDetectColorScheme": true` so that `workbench.preferredLightColorTheme` and `workbench.preferredDarkColorTheme` take effect.

Okay, i guess on the same block right?

**Comment by Shulammite-Aso** [comment]
Just made the update @jeanp413

**Comment by akosyakov** [comment]
@jeanp413 I don't think we need to change `window.autoDetectColorScheme`. It is more like if a user enables it then it should use gitpod themes by default, but we should restrain from changing defaults otherwise.

**Comment by jeanp413** [comment]
@akosyakov Good point, but right now we don't sync user theme set in the dashboard to the editor so it will keep using the Light theme regardless of what the user sets in his settings. There's this issue https://github.com/gitpod-io/gitpod/issues/3982 but got closed bucause it was stale

**Comment by akosyakov** [comment]
@jeanp413 It was discussed internally that we don't do synching between dashboard and editor: https://gitpod.slack.com/archives/C01KGM9BH54/p1635256498135500?thread_ts=1635187855.111600&cid=C01KGM9BH54

**Comment by jeanp413** [comment]
@Shulammite-Aso I will revert the last commit, rebase and then merge. Thanks

**Review by jeanp413 — APPROVED** [review]

**Pull request merged**
